### ISSUE TITLE
Version number build failure

### ISSUE THREAD

**Issue by vblm** [FictitiousFrode/AIF#44]
I'm getting this build failure from the include. Looks like inform is expecting 6 digits in the second part of the version number. Adding an extra number allowed it to build.

> Problem. You wrote 'Version 2/16122 of Erotic Storytelling by Fictitious Frode'  : but a version number must have the form N/DDDDDD, as in the example '2/040426' for release 2 made on 26 April 2004. (The DDDDDD part is optional, so '3' is a legal version number too. N must be between 1 and 999: in particular, there is no version 0.)

**Comment by FictitiousFrode** [comment]
Fixed it.
