### ISSUE TITLE
Consent in 6L38

### ISSUE THREAD

**Issue by vblm** [FictitiousFrode/AIF#5]
The Consent extension fails to compile with the following error:

In **Part 1 - Consent Rules** in the extension **Consent by Fictitious Frode:**

**Problem.** The sentence 'Dummy-consenting-action is consensual'   appears to say two things are the same - I am reading 'Dummy-consenting-action' and 'consensual' as two different things, and therefore it makes no sense to say that one is the other: it would be like saying that 'Aeschylus is Euripides'. It would be all right if the second thing were the name of a kind, perhaps with properties: for instance 'Underworld is a lighted room' says that something called Underworld exists and that it is a 'room', which is a kind I know about, combined with a property called 'lighted' which I also know about.

**Comment by FictitiousFrode** [comment]
Ok, this one is a bit puzzling, as that sentence was put there explicitly to make it compile. As far as I can tell, there is no way to tell Inform that something describes an action without actually describing it.
It seems as the error is as "simple" as a last-minute rename from Dummy-action-consenting to Dummy-consenting-action has left Inform confused about it being a verb.
