### ISSUE TITLE
Garments in 6L38

### ISSUE THREAD

**Issue by vblm** [FictitiousFrode/AIF#6]
Another compile error in Garments:

In **Book 2 - Actions, Part 2.5 - Looking under** in the extension **Garments by Fictitious Frode:**

**Problem.** You wrote 'If something (called the underwear) underlies the noun, say "[We] [peek] at [the underwear]. Yup, still there." (A)'  : but lettered responses can only be used in named rules, not in any of the other contexts in which quoted text can appear.

---

**Problem.** You wrote 'Otherwise say "Just [us] in there." (B)'  : again, lettered responses can only be used in named rules

**Comment by FictitiousFrode** [comment]
Another last-minute cleanup that causes problems, easy to fix.
