### ISSUE TITLE
'x his/her' shortcut does not work on parts of every person.

### ISSUE THREAD

**Issue by vblm** [FictitiousFrode/AIF#8]
Here's a minimal test case:

``` inform7
"Test Adventure" by "vblm"

Include Erotic Story Actions by Fictitious Frode.

The test subject is a man. The player is the test subject.

A head is a part of every person.

The Test Chamber is a room.

The Scientist is a woman in the Test Chamber.

Test me with "x her head./x the scientist's head."
```

**Comment by FictitiousFrode** [comment]
I'll have a look at it, but this looks to be part of how Inform deals with attachments. I might be able to get around it with an understand rule.

On a seperate note, it's a good idea to declare all characters before invoking body parts.

**Comment by FictitiousFrode** [comment]
This is supported in the remade extension.
